workflows:
  totv-plus-fix:
    name: ToTV+ Build Success
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.22.2 # نسخة مستقرة جداً
      java: 17
    scripts:
      - name: Fix Flutter Tooling Error
        script: |
          # مسح أي إعدادات قديمة تسبب تعارض
          flutter clean
          flutter pub get
          cd android
          # هذا السطر يخبر Gradle بتجاهل أخطاء التوافق في مكتبات فلاتر
          echo "android.suppressUnsupportedCompileSdk=34" >> local.properties
          chmod +x gradlew
          cd ..
      - name: Build Android APK
        script: |
          # بناء APK نسخة Release (وهي التي تعمل على هاتفك)
          # نستخدم --no-pub لأننا قمنا بعمل pub get مسبقاً
          flutter build apk --release --no-tree-shake-icons --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
